SampleName: "FHC_numu"
SampleType: "BeamFD"
POT: 1.3628319e+23
SelectionCuts:
  - KinematicStr: "TrueXPos"
    Bounds: [ -310.0, 310.0 ]
  - KinematicStr: "TrueYPos"
    Bounds: [ -550.0, 550.0 ]
  - KinematicStr: "TrueZPos"
    Bounds: [ 50.0, 1244.0 ]
  - KinematicStr: "CVNNumu"
    Bounds: [ 0.5, 999 ]

Binning:
  Axes:
# Appropriate values for VarStr
# TrueNeutrinoEnergy
# RecoNeutrinoEnergy
# CVNNumu
# CVNNue
# q0
# q3
# ERecQE
# ELepRec
# EHadRec
    - VarStr: "q0" 
      Uniform: [3,0,1.5]
      Title: "q_{0} [GeV]"
    - VarStr: "q3" 
      Uniform: [3,0,1.5]
      Title: "q_{3} [GeV]"
    #- VarStr: "ELepRec" 
     # Uniform: [25,0,5]
      #Title: "E_{lep.}^{Rec} [GeV]"
    #- VarStr: "EHadRec" 
     # Uniform: [25,0,5]
      #Title: "E_{had.}^{Vis} [GeV]"
    #- VarStr: "RecoNeutrinoEnergy" 
     # Uniform: [10,0.5,5.5]
      #Title: "E_{#nu}^{Rec} [GeV]"
  # if you want to use the generic binning with a single 
  # axis, useful for calculated VarStr that cannot be referenced
  ForceGeneric: True

DUNESampleBools:
  iselike: no
InputFiles:
  mtupleprefix: "inputs/DUNE_CAF_files/FD_FHC_ger_"
  mtuplesuffix: "_numuselec.root"
  # splineprefix: "inputs/DUNE_spline_files/FD_FHC_ger_"
  # splinesuffix: "_numuselec_splines.root"
DetID: 24
NuOsc:
  NuOscConfigFile: "configs/NuOsc/CUDAProb3Linear.yaml"
NSubSamples: 12
SubSamples:
  - name: "FHC_numu_x_numu"
    mtuplefile: "numu_x_numu"
    # splinefile: "numu_x_numu"
    samplevecno: 0
    nutype: 14
    oscnutype: 14
    signal: false
  - name: "FHC_nue_x_nue"
    mtuplefile: "nue_x_nue"
    # splinefile: "nue_x_nue"
    samplevecno: 1
    nutype: 12
    oscnutype: 12
    signal: false
  - name: "FHC_numubar_x_numubar"
    mtuplefile: "numubar_x_numubar"
    # splinefile: "numubar_x_numubar"
    samplevecno: 2
    nutype: -14
    oscnutype: -14
    signal: false
  - name: "FHC_nuebar_x_nuebar"
    mtuplefile: "nuebar_x_nuebar"
    # splinefile: "nuebar_x_nuebar"
    samplevecno: 3
    nutype: -12
    oscnutype: -12
    signal: false
  - name: "FHC_numu_x_nue"
    mtuplefile: "numu_x_nue"
    # splinefile: "numu_x_nue"
    samplevecno: 4
    nutype: 14
    oscnutype: 12
    signal: true
  - name: "FHC_numubar_x_nuebar"
    mtuplefile: "numubar_x_nuebar"
    # splinefile: "numubar_x_nuebar"
    samplevecno: 5
    nutype: -14
    oscnutype: -12 
    signal: true
  - name: "FHC_nue_x_numu"
    mtuplefile: "nue_x_numu"
    # splinefile: "nue_x_numu"
    samplevecno: 6
    nutype: 12
    oscnutype: 14
    signal: true
  - name: "FHC_nuebar_x_numubar"
    mtuplefile: "nuebar_x_numubar"
    # splinefile: "nuebar_x_numubar"
    samplevecno: 7
    nutype: -12
    oscnutype: -14
    signal: true
  - name: "FHC_numu_x_nutau"
    mtuplefile: "numu_x_nutau"
    # splinefile: "numu_x_nutau"
    samplevecno: 8
    nutype: 14
    oscnutype: 16
    signal: true
  - name: "FHC_nue_x_nutau"
    mtuplefile: "nue_x_nutau"
    # splinefile: "nue_x_nutau"
    samplevecno: 9
    nutype: 12
    oscnutype: 16
    signal: true
  - name: "FHC_numubar_x_nutaubar"
    mtuplefile: "numubar_x_nutaubar"
    # splinefile: "numubar_x_nutaubar"
    samplevecno: 10
    nutype: -14
    oscnutype: -16
    signal: true
  - name: "FHC_nuebar_x_nutaubar"
    mtuplefile: "nuebar_x_nutaubar"
    # splinefile: "nuebar_x_nutaubar"
    samplevecno: 11
    nutype: -12
    oscnutype: -16
    signal: true
