Systematics:
- Systematic:
    DetID: 1
    Error: 0.5
    FlatPrior: false
    KinematicCuts:
    - ERec_minus_Etrue:
      - 0.0
      - 2.0
    - q0:
      - 0.0
      - 0.5
    Names:
      FancyName: deltaE_0
      ParameterName: deltaE_0
    ParameterBounds:
    - -9999.0
    - 9999.0
    ParameterValues:
      Generated: 1.0
      PreFitValue: 1.0
    StepScale:
      MCMC: 0.1
    Type: Norm
    ParameterGroup: Xsec