Systematics:
- Systematic:
    DetID: 24
    Error: 0.5
    FlatPrior: false
    KinematicCuts:
    - q0:
      - 0.0
      - 0.5
    - q3:
      - 0.0
      - 0.5
    Names:
      FancyName: q0q3_1
      ParameterName: q0q3_1
    ParameterBounds:
    - -9999.0
    - 9999.0
    ParameterValues:
      Generated: 1.0
      PreFitValue: 1.0
    StepScale:
      MCMC: 0.1
    Type: Norm
    ParameterGroup: Xsec
- Systematic:
    DetID: 24
    Error: 0.5
    FlatPrior: false
    KinematicCuts:
    - q0:
      - 0.5
      - 1.0
    - q3:
      - 0.0
      - 0.5
    Names:
      FancyName: q0q3_2
      ParameterName: q0q3_2
    ParameterBounds:
    - -9999.0
    - 9999.0
    ParameterValues:
      Generated: 1.0
      PreFitValue: 1.0
    StepScale:
      MCMC: 0.1
    Type: Norm
    ParameterGroup: Xsec
- Systematic:
    DetID: 24
    Error: 0.5
    FlatPrior: false
    KinematicCuts:
    - q0:
      - 1.0
      - 1.5
    - q3:
      - 0.0
      - 0.5
    Names:
      FancyName: q0q3_3
      ParameterName: q0q3_3
    ParameterBounds:
    - -9999.0
    - 9999.0
    ParameterValues:
      Generated: 1.0
      PreFitValue: 1.0
    StepScale:
      MCMC: 0.1
    Type: Norm
    ParameterGroup: Xsec
- Systematic:
    DetID: 24
    Error: 0.5
    FlatPrior: false
    KinematicCuts:
    - q0:
      - 0.0
      - 0.5
    - q3:
      - 0.5
      - 1.0
    Names:
      FancyName: q0q3_4
      ParameterName: q0q3_4
    ParameterBounds:
    - -9999.0
    - 9999.0
    ParameterValues:
      Generated: 1.0
      PreFitValue: 1.0
    StepScale:
      MCMC: 0.1
    Type: Norm
    ParameterGroup: Xsec
- Systematic:
    DetID: 24
    Error: 0.5
    FlatPrior: false
    KinematicCuts:
    - q0:
      - 0.5
      - 1.0
    - q3:
      - 0.5
      - 1.0
    Names:
      FancyName: q0q3_5
      ParameterName: q0q3_5
    ParameterBounds:
    - -9999.0
    - 9999.0
    ParameterValues:
      Generated: 1.0
      PreFitValue: 1.0
    StepScale:
      MCMC: 0.1
    Type: Norm
    ParameterGroup: Xsec
- Systematic:
    DetID: 24
    Error: 0.5
    FlatPrior: false
    KinematicCuts:
    - q0:
      - 1.0
      - 1.5
    - q3:
      - 0.5
      - 1.0
    Names:
      FancyName: q0q3_6
      ParameterName: q0q3_6
    ParameterBounds:
    - -9999.0
    - 9999.0
    ParameterValues:
      Generated: 1.0
      PreFitValue: 1.0
    StepScale:
      MCMC: 0.1
    Type: Norm
    ParameterGroup: Xsec
- Systematic:
    DetID: 24
    Error: 0.5
    FlatPrior: false
    KinematicCuts:
    - q0:
      - 0.0
      - 0.5
    - q3:
      - 1.0
      - 1.5
    Names:
      FancyName: q0q3_7
      ParameterName: q0q3_7
    ParameterBounds:
    - -9999.0
    - 9999.0
    ParameterValues:
      Generated: 1.0
      PreFitValue: 1.0
    StepScale:
      MCMC: 0.1
    Type: Norm
    ParameterGroup: Xsec
- Systematic:
    DetID: 24
    Error: 0.5
    FlatPrior: false
    KinematicCuts:
    - q0:
      - 0.5
      - 1.0
    - q3:
      - 1.0
      - 1.5
    Names:
      FancyName: q0q3_8
      ParameterName: q0q3_8
    ParameterBounds:
    - -9999.0
    - 9999.0
    ParameterValues:
      Generated: 1.0
      PreFitValue: 1.0
    StepScale:
      MCMC: 0.1
    Type: Norm
    ParameterGroup: Xsec
- Systematic:
    DetID: 24
    Error: 0.5
    FlatPrior: false
    KinematicCuts:
    - q0:
      - 1.0
      - 1.5
    - q3:
      - 1.0
      - 1.5
    Names:
      FancyName: q0q3_9
      ParameterName: q0q3_9
    ParameterBounds:
    - -9999.0
    - 9999.0
    ParameterValues:
      Generated: 1.0
      PreFitValue: 1.0
    StepScale:
      MCMC: 0.1
    Type: Norm
    ParameterGroup: Xsec