# for each list specify:
# isrhc = "true for rhc or false for fhc"; #default to false
# mtupleprefix = "common part at beginning of path to mtuple files"
# mtuplesuffix = "common part at end of path to mtuple files"
# splineprefix = "common part at beginning of path to spline files"
# splinesuffix = "common part at endof path to spline files"
# up_bnd = "upper boundary on erec" #deault to 30.
# isfitqun = true for fitqun variable samples false otherwise #default to true
#Add samples to the sample list as shown below
SampleName: "ND_FHC_CCnumu"
SampleType: "BeamFD"
SelectionCuts:
POT: 0.00e+00
SelectionCuts:
  - KinematicStr: "TrueXPos"
    Bounds: [ -310.0, 310.0 ]
  - KinematicStr: "TrueYPos"
    Bounds: [ -550.0, 550.0 ]
  - KinematicStr: "TrueZPos"
    Bounds: [ 50.0, 1244.0 ]
  - KinematicStr: "CVNNumu"
    Bounds: [ 0.5, 999 ]
Binning:
  Axes:
    - VarStr: "RecoNeutrinoEnergy" 
      Uniform: [10,0.1,5.5]
      Title: "E_{#nu}^{Rec} [GeV]"
    - VarStr: "p_lep" 
      Uniform: [20,0,8]
      Title: "p_{lep.}^{Rec} [GeV]"
    - VarStr: "theta_lep" 
      Uniform: [6,0,3]
      Title: "#theta_{lep.}^{Rec} [GeV]"
  ForceGeneric: True
DUNESampleBools:
  iselike: no
NuOsc:
  NuOscConfigFile: "configs/NuOsc/CUDAProb3Linear.yaml"
InputFiles:
  mtupleprefix: "/pnfs/dune/persistent/users/chasnip/NDCAF_OnAxisHadd/FHC/"
  mtuplesuffix: ""
  splineprefix: "" 
  splinesuffix: ""
SampleCuts:
  up_bnd: 100.
NSubSamples: 1
DetID: 1
SubSamples:
  - name: "CAFv7_1.75m_08_FHC.root"
    mtuplefile: "CAFv7_1.75m_08_FHC.root"
    splinefile: ""
    samplevecno: 0
    nutype: 14
    oscnutype: 14
    signal: false