General:
  IncludeFD: true
  IncludeND: true
  FDPOT: 1.3628319e+23
  NDPOT: 3.85e+21
  #### Asimov A ####
  OscParams: [0.307, 0.528, 0.0218, 7.53e-5, 2.509e-3, -1.601]
  # NuFit 4.0 NH ####
  #OscParams: [0.310, 0.582, 0.0224, 7.39e-5, 2.525e-3, -2.498]
  Systematics:
    XsecCovFile: "/home/abipeake/Mach3/MaCh3_DUNE/utils/xsecMatrixMaker/xsec_abisversion_q0.root" #"inputs/XSecCovNoSplineParams.root"
    XsecCovName: "xsec_cov"
    XsecStepScale: 0.1
    XsecAtGen: false 
    OscCovFile: "inputs/osc_covariance_DUNE_PDG2021_v1.root"
    OscCovName: "osc_cov"
    OscStepScale: 0.045
  Output:
    FileName: "Results/xsec_parameter_1Dq3_2D_2sigma_151024.root"