# for each list specify:
# isrhc = "true for rhc or false for fhc"; #default to false
# mtupleprefix = "common part at beginning of path to mtuple files"
# mtuplesuffix = "common part at end of path to mtuple files"
# splineprefix = "common part at beginning of path to spline files"
# splinesuffix = "common part at endof path to spline files"
# up_bnd = "upper boundary on erec" #deault to 30.
# isfitqun = true for fitqun variable samples false otherwise #default to true
#Add samples to the sample list as shown below
# {
# 	name = "descriptive name for sample";
# 	mtuplefile = "path to mtuple file";
# 	splinefile  = "path to splinefile"; #!!NB MUST BE COMPATIBLE WITH BINNING OPTION SPECIFIED IN EXECUTABLE
# 	samplevecno = which number in the skmcsamples array should this go in;
# 	nutype = "nutype before oscillation";
# 	oscnutype = "nutype after oscillation";
# 	signal = true for signal samples;,
# },
SampleName: "ND_FHC_CCnumu"
SelectionCuts:
Binning:
  BinningOpt: 1
  XVarBins: [0.,  0.5,  1.,  1.25, 1.5, 1.75, 2., 2.25, 2.5, 2.75, 3., 3.25, 3.5, 3.75, 4., 5., 6., 10.]
  YVarBins: [0., 0.1, 0.2, 0.3, 0.4, 0.6, 1.1]
SampleBools:
  isrhc: no
  isnd: yes
  iselike: no
InputFiles:
  mtupleprefix: "inputs/DUNE_ND_CAF_files/ND_FHC_ger_"
  mtuplesuffix: "_fv_ccinc_q.root"
  splineprefix: "" #"inputs/DUNE_ND_spline_files/ND_FHC_ger_"
  splinesuffix: "" #"_splines.root"
InputFiles:
  mtupleprefix: "inputs/DUNE_ND_CAF_files/ND_FHC_ger_"
  mtuplesuffix: "_fv_ccinc_q.root"
  splineprefix: "inputs/DUNE_ND_spline_files/ND_FHC_ger_"
  splinesuffix: "_splines.root"
SampleCuts:
  up_bnd: 100.
NSubSamples: 16
DetID: 1
SubSamples:
  - name: "FHC_numu_x_numu_0"
    mtuplefile: "numu_x_numu_0"
    splinefile: "numu_x_numu_0"
    samplevecno: 0
    nutype: 14
    oscnutype: 14
    signal: false
  - name: "FHC_numu_x_numu_1"
    mtuplefile: "numu_x_numu_1"
    splinefile: "numu_x_numu_1"
    samplevecno: 1
    nutype: 14
    oscnutype: 14
    signal: false
  - name: "FHC_numu_x_numu_2"
    mtuplefile: "numu_x_numu_2"
    splinefile: "numu_x_numu_2"
    samplevecno: 2
    nutype: 14
    oscnutype: 14
    signal: false
  - name: "FHC_numu_x_numu_3"
    mtuplefile: "numu_x_numu_3"
    splinefile: "numu_x_numu_3"
    samplevecno: 3
    nutype: 14
    oscnutype: 14
    signal: false
  - name: "FHC_numu_x_numu_4"
    mtuplefile: "numu_x_numu_4"
    splinefile: "numu_x_numu_4"
    samplevecno: 4
    nutype: 14
    oscnutype: 14
    signal: false
  - name: "FHC_numu_x_numu_5"
    mtuplefile: "numu_x_numu_5"
    splinefile: "numu_x_numu_5"
    samplevecno: 5
    nutype: 14
    oscnutype: 14
    signal: false
  - name: "FHC_numu_x_numu_6"
    mtuplefile: "numu_x_numu_6"
    splinefile: "numu_x_numu_6"
    samplevecno: 6
    nutype: 14
    oscnutype: 14
    signal: false
  - name: "FHC_numu_x_numu_7"
    mtuplefile: "numu_x_numu_7"
    splinefile: "numu_x_numu_7"
    samplevecno: 7
    nutype: 14
    oscnutype: 14
    signal: false
  - name: "FHC_numu_x_numu_8"
    mtuplefile: "numu_x_numu_8"
    splinefile: "numu_x_numu_8"
    samplevecno: 8
    nutype: 14
    oscnutype: 14
    signal: false
  - name: "FHC_numu_x_numu_9"
    mtuplefile: "numu_x_numu_9"
    splinefile: "numu_x_numu_9"
    samplevecno: 9
    nutype: 14
    oscnutype: 14
    signal: false
  - name: "FHC_numu_x_numu_10"
    mtuplefile: "numu_x_numu_10"
    splinefile: "numu_x_numu_10"
    samplevecno: 10
    nutype: 14
    oscnutype: 14
    signal: false
  - name: "FHC_numu_x_numu_11"
    mtuplefile: "numu_x_numu_11"
    splinefile: "numu_x_numu_11"
    samplevecno: 11
    nutype: 14
    oscnutype: 14
    signal: false
  - name: "FHC_numu_x_numu_12"
    mtuplefile: "numu_x_numu_12"
    splinefile: "numu_x_numu_12"
    samplevecno: 12
    nutype: 14
    oscnutype: 14
    signal: false
  - name: "FHC_nue_x_nue"
    mtuplefile: "nue_x_nue"
    splinefile: "nue_x_nue"
    samplevecno: 13
    nutype: 12
    oscnutype: 12
    signal: false
  - name: "FHC_numubar_x_numubar"
    mtuplefile: "numubar_x_numubar"
    splinefile: "numubar_x_numubar"
    samplevecno: 14
    nutype: -14
    oscnutype: -14
    signal: false
  - name: "FHC_nuebar_x_nuebar"
    mtuplefile: "nuebar_x_nuebar"
    splinefile: "nuebar_x_nuebar"
    samplevecno: 15
    nutype: -12
    oscnutype: -12
    signal: false
