# for each list specify:
# isrhc = "true for rhc or false for fhc"; #default to false
# mtupleprefix = "common part at beginning of path to mtuple files"
# mtuplesuffix = "common part at end of path to mtuple files"
# splineprefix = "common part at beginning of path to spline files"
# splinesuffix = "common part at endof path to spline files"
# up_bnd = "upper boundary on erec" #deault to 30.
# isfitqun = true for fitqun variable samples false otherwise #default to true
#Add samples to the sample list as shown below
# {
# name = "descriptive name for sample";
# mtuplefile = "path to mtuple file";
# splinefile  = "path to splinefile"; #!!NB MUST BE COMPATIBLE WITH BINNING OPTION SPECIFIED IN EXECUTABLE
# samplevecno = which number in the skmcsamples array should this go in;
# nutype = "nutype before oscillation";
# oscnutype = "nutype after oscillation";
# signal = true for signal samples;,
# },OA3DHistogram
SampleName: "ND_FHC_CCnumu"
SelectionCuts:
  - KinematicStr: "kBinningin2D" 
    Bounds: [ 0.0, 1000.0]
Binning:
  BinningOpt: 3
  NTotalBins: 30
  YVarBins: [0.0, 1.0, 2.0, 3.0, 4.0,5.0]
  #XVarBins: 226 #doc["Binning"]["NTotalBins"].as<int>();
  XVarBins: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122]
SampleBools:
  isrhc: no
  #isnd: yes
  iselike: no
SampleName: "ND_FHC_CCnumu"
InputFiles:
  mtupleprefix: "/home/abipeake/Mach3/MaCh3_DUNE/inputs/DUNE_OA_CAF_new/"
  mtuplesuffix: ""
  splineprefix: ""
  splinesuffix: ""
SampleCuts:
  up_bnd: 30.
DetID: 1